server:
  port: 8082

event:
  bus:
    activemq:
      listener-package: com.jinternals.activemq.consumer.listeners
      event-package: com.jinternals.activemq.consumer.events
      broker:
        url: tcp://localhost:61616
        user-name: admin
        password: admin
      producer:
        enabled: false
      consumer:
        destination: Event.Bus.Demo
        concurrency: 1-3

