version: '3.5'


services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./config/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    networks:
      rabbitmq-network:
        ipv4_address: 15.5.0.2


  rabbitmq-todo-query-1:
    image: jinternals/rabbitmq-todo-query
    container_name: rabbitmq-todo-query-1
    environment:
      - INSTANCE-INDEX=1
    ports:
      - 8081:8080
    networks:
      rabbitmq-network:
        ipv4_address: 15.5.0.3

  rabbitmq-todo-query-2:
    image: jinternals/rabbitmq-todo-query
    container_name: rabbitmq-todo-query-2
    environment:
      - INSTANCE-INDEX=2
    ports:
      - 8082:8080
    networks:
      rabbitmq-network:
        ipv4_address: 15.5.0.4

  rabbitmq-todo-command:
    image: jinternals/rabbitmq-todo-command
    container_name: rabbitmq-todo-command
    ports:
      - 8083:8080
    networks:
      rabbitmq-network:
        ipv4_address: 15.5.0.5

networks:
  rabbitmq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 15.5.0.0/16
