version: '3.5'

services:
  activemq:
    image: jinternals/activemq
    build: ./config/activemq/
    container_name: activemq
    ports:
      - 8161:8161
      - 61616:61616
    volumes:
      - ./config/activemq/activemq.xml:/opt/activemq/conf/activemq.xml
    networks:
      activemq-network:
        ipv4_address: 14.5.0.2

networks:
  activemq-network:
    driver: bridge
    ipam:
      config:
        - subnet: 14.5.0.0/16