server:
  port: 8080

event:
  bus:
    activemq:
      listener-package: com.jinternals.activemq.consumer.listeners
      event-package: com.jinternals.activemq.consumer.events
      broker:
        url: tcp://activemq:61616
        user-name: admin
        password: admin
      consumer:
        destination: Event.Bus.Demo
        concurrency: 1-3

