server:
  port: 8080

event:
  bus:
    activemq:
      listener-package: com.jinternals.activemq.consumer.events
      event-package: com.jinternals.activemq.consumer.events
      exclusive-consumer: true
      broker:
        url: tcp://activemq:61616
        user-name: admin
        password: admin
      producer:
        destination: Event.Bus
        pub-sub: false
      consumer:
        enabled: false


